### ISSUE TITLE
Startup fails with anyio 4.15: module 'anyio' has no attribute 'from_thread'

### ISSUE THREAD

**Issue by dfguerrerom** [widgetti/solara#1197]
anyio 4.15.0 (released 2026-09-02) made the top-level imports lazy ([anyio#1169](https://github.com/agronholm/anyio/pull/1169)). The lookup table is built from the `if TYPE_CHECKING:` block of `anyio/__init__.py`, and `from_thread` is not in it, so a bare `import anyio` no longer makes `anyio.from_thread` available as an attribute.

`solara/server/starlette.py` imports only `anyio` and then reads `anyio.from_thread` in an annotation that is evaluated when the class body runs, so the server fails to start:

```
File ".../solara/server/starlette.py", line 114, in <module>
  class WebsocketWrapper(websocket.WebsocketWrapper):
File ".../solara/server/starlette.py", line 117, in WebsocketWrapper
  def __init__(self, ws: starlette.websockets.WebSocket, portal: Optional[anyio.from_thread.BlockingPortal]) -> None:
File ".../anyio/_lazyimport.py", line 41, in __getattr__
  raise AttributeError(
AttributeError: module 'anyio' has no attribute 'from_thread'
```

**Reproduction** (clean venv):

```
$ pip install "anyio==4.15.0"
$ python -c "import anyio; anyio.from_thread.BlockingPortal"
AttributeError: module 'anyio' has no attribute 'from_thread'

$ python -c "import anyio.from_thread; print(anyio.from_thread.BlockingPortal)"
<class 'anyio.from_thread.BlockingPortal'>       # explicit submodule import still works
```

Works on anyio 4.14.2, fails on 4.15.0. Seen with solara 1.61.0 on Python 3.12.

**Suggested fix:** import the submodule explicitly in `solara/server/starlette.py`:

```python
import anyio.from_thread
```

A quick grep for other bare `anyio.<submodule>` attribute accesses would be worth doing, since they have the same failure mode.

Workaround in the meantime: pin `anyio<4.15`.
